FROM maven:3.9.12-amazoncorretto-25-alpine AS build

WORKDIR /app
COPY . .

RUN mvn package -DskipTests

FROM amazoncorretto:25-alpine3.22

RUN apk add --no-cache python3 py3-requests

COPY --from=build /app/target/backend-java-1.0.jar app.jar
COPY --from=build /app/src/main/python/sudoku_scraper.py /src/main/python/sudoku_scraper.py
COPY --from=build /app/db/sudokugames.db /db/sudokugames.db

EXPOSE 8080
CMD ["java", "--enable-native-access=ALL-UNNAMED", "-jar", "app.jar"]