# Use an official Maven image to build the application
FROM maven:3.9.9-eclipse-temurin-21-jammy AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the project files into the container
COPY . .

# Build the application
RUN mvn package -DskipTests

# Use an official OpenJDK runtime image to run the application
FROM eclipse-temurin:21-jre-alpine

# Install Python
RUN apk add --no-cache python3 py3-requests

# Copy the built JAR file from the build stage
COPY --from=build /app/target/backend-java-1.0.jar app.jar

# Copy the Python script and SQLite database into the container
COPY sudoku_scraper/sudoku_scraper.py sudoku_scraper/sudoku_scraper.py
COPY sudokugames.db sudokugames.db

# Expose the port your application runs on
EXPOSE 8080

# Command to run the application
CMD ["java", "--enable-native-access=ALL-UNNAMED", "-jar", "app.jar"]